torch_classes = ['Lima', 'Lawther', 'Daddario', 'Morte', 'Crew', 'Samberg', 'Hathaway', 'Mackie', 'Lavigne', 'Affleck', 'Gates', 'Morley', 'Thwaites', 'Smith', 'Larson', 'Evans', 'Hemsworth', 'Pratt', 'Bale', 'Ronaldo', 'Panabaker', 'Purcell', 'Johnson', 'Taylor', 'Lail', 'Clarke', 'Stone', 'Watson', 'Paltrow', 'Cavil', 'Jackman', 'Lavi', 'Shayk', 'Mcdorman', 'Momoa', 'Lawrence', 'Renner', 'Barden', 'Fallon', 'Depp', 'Radnor', 'Mcphee', 'Langford', 'Reeves', 'Ritter', 'DiCaprio', 'Reinhart', 'Morgan', 'Messi', 'Lerman', 'Petsch', 'Williams', 'Pedraza', 'Avgeropoulos', 'Ruffalo', 'Zuckerberg', 'Fox', 'Cyrus', 'Brown', 'Baccarin', 'Freeman', 'Hilker', 'Dormer', 'Portman', 'Harris', 'Alonso', 'Badgley', 'Malek', 'Ferguson', 'Harmon', 'Rihanna', 'Niro', 'Jr', 'Callies', 'Gomez', 'Mebarak', 'Turner', 'Amell', 'Swift', 'Cruise', 'Hardy', 'Hiddleston', 'Holland', 'Middleton', 'Corbero', 'Miller', 'Efron', 'Zendaya', 'Saldana', 'carey', 'heard', 'obama', 'palvin', 'mendes', 'olsen', 'page', 'musk', 'gadot', 'gustin', 'bezos', 'shipka', 'robbie', 'fumero', 'johansson', 'ellis']
full_name_classes = ['Adriana_Lima', 'Alex_Lawther', 'Alexandra_Daddario', 'Alvaro_Morte', 'Amanda_Crew', 'Andy_Samberg', 'Anne_Hathaway', 'Anthony_Mackie', 'Avril_Lavigne', 'Ben_Affleck', 'Bill_Gates', 'Bobby_Morley', 'Brenton_Thwaites', 'Brian_J._Smith', 'Brie_Larson', 'Chris_Evans', 'Chris_Hemsworth', 'Chris_Pratt', 'Christian_Bale', 'Cristiano_Ronaldo', 'Danielle_Panabaker', 'Dominic_Purcell', 'Dwayne_Johnson', 'Eliza_Taylor', 'Elizabeth_Lail', 'Emilia_Clarke', 'Emma_Stone', 'Emma_Watson', 'Gwyneth_Paltrow', 'Henry_Cavil', 'Hugh_Jackman', 'Inbar_Lavi', 'Irina_Shayk', 'Jake_Mcdorman', 'Jason_Momoa', 'Jennifer_Lawrence', 'Jeremy_Renner', 'Jessica_Barden', 'Jimmy_Fallon', 'Johnny_Depp', 'Josh_Radnor', 'Katharine_Mcphee', 'Katherine_Langford', 'Keanu_Reeves', 'Krysten_Ritter', 'Leonardo_DiCaprio', 'Lili_Reinhart', 'Lindsey_Morgan', 'Lionel_Messi', 'Logan_Lerman', 'Madelaine_Petsch', 'Maisie_Williams', 'Maria_Pedraza', 'Marie_Avgeropoulos', 'Mark_Ruffalo', 'Mark_Zuckerberg', 'Megan_Fox', 'Miley_Cyrus', 'Millie_Bobby_Brown', 'Morena_Baccarin', 'Morgan_Freeman', 'Nadia_Hilker', 'Natalie_Dormer', 'Natalie_Portman', 'Neil_Patrick_Harris', 'Pedro_Alonso', 'Penn_Badgley', 'Rami_Malek', 'Rebecca_Ferguson', 'Richard_Harmon', 'Rihanna', 'Robert_De_Niro', 'Robert_Downey_Jr', 'Sarah_Wayne_Callies', 'Selena_Gomez', 'Shakira_Isabel_Mebarak', 'Sophie_Turner', 'Stephen_Amell', 'Taylor_Swift', 'Tom_Cruise', 'Tom_Hardy', 'Tom_Hiddleston', 'Tom_Holland', 'Tuppence_Middleton', 'Ursula_Corbero', 'Wentworth_Miller', 'Zac_Efron', 'Zendaya', 'Zoe_Saldana', 'alycia_dabnem_carey', 'amber_heard', 'barack_obama', 'barbara_palvin', 'camila_mendes', 'elizabeth_olsen', 'ellen_page', 'elon_musk', 'gal_gadot', 'grant_gustin', 'jeff_bezos', 'kiernen_shipka', 'margot_robbie', 'melissa_fumero', 'scarlett_johansson', 'tom_ellis']

data_dict = {}

# Old code
for idx, short_name in enumerate(torch_classes):
    data_dict[idx] = {"short_name": short_name, "full_name": full_name_classes[idx]}


# Result
# {0: {'short_name': 'Lima', 'full_name': 'Adriana_Lima'}, 
# 1: {'short_name': 'Lawther', 'full_name': 'Alex_Lawther'}, 
# 2: {'short_name': 'Daddario', 'full_name': 'Alexandra_Daddario'}, 
# 3: {'short_name': 'Morte', 'full_name': 'Alvaro_Morte'}, 
# 4: {'short_name': 'Crew', 'full_name': 'Amanda_Crew'}}